name: google_maps_webservice
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 0.0.20-nullsafety.6
homepage: https://github.com/lejard-h/google_maps_webservice

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
 

dev_dependencies:
  test: ^1.25.2
  pedantic: ^1.10.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  coverage: ^1.7.2
